### ISSUE TITLE
Second form not check for usage of old construction

### ISSUE THREAD

**Issue by senpl** [cmstead/jsLearnerForms#3]
Second form pass from the beginning. It should fail and step by step be improved to new forms. Currently it is not usable really different from form 1.

**Comment by cmstead** [comment]
Hi, sorry for the delay on response.  This has been a consideration for some time now. I have a few ideas on how I might do this, but I just haven't been able to set aside the time just yet. I'm making some really important changes to make setup easier and running the forms clearer. I also plan to start making videos which will make the movements more obvious.

Thank you for providing feedback.  I'll update this thread as I get more work done.

**Comment by cmstead** [comment]
Just an update: The tests are now starting to verify refactorings as they are done.  Sum, for instance, verifies you create the new function, and ensures everything is handled in a forEach with a lambda function.  Please try out the new tests and let me know if you have any feedback.

The second form updates are still underway, but you can test run the refactoring steps under two different test suites.

**Comment by senpl** [comment]
I like it better. I also like clearer instruction on README page. Great work.
My suggestion:
I guess typeof greeting=="string" should also be accepted, but I know it probably should be '==='. But afaik many students use ==.

**Comment by cmstead** [comment]
I can appreciate where you're coming from.  That said, I am inclined to try and lead people to a safer, more reliable development experience.  I'll give the double-equal syntax consideration.

Also, I'm glad you're liking it better.  I'm feeling the same way.  It feels much more guided and intentional.  I appreciate the feedback and suggestions.  Keep them coming!

(Closing this issue as the new direction should resolve the concern. Feel free to open new issues as they arise)
